// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKtSsZ67inFy0ruAU1DW42nl5X8kbgkMk',
    appId: '1:92826655668:web:ac67b7af1568d2b4f170e1',
    messagingSenderId: '92826655668',
    projectId: 'twitter-task-6e6b1',
    authDomain: 'twitter-task-6e6b1.firebaseapp.com',
    storageBucket: 'twitter-task-6e6b1.firebasestorage.app',
    measurementId: 'G-BXFE5VNVK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3VBBaQg9DxsUzR9E-ndRXaoj3eKCIqdQ',
    appId: '1:92826655668:android:892f5b82a4ba95f1f170e1',
    messagingSenderId: '92826655668',
    projectId: 'twitter-task-6e6b1',
    storageBucket: 'twitter-task-6e6b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqk0lvP3XC3j2Xhl_vqULC01DfzZTzP-A',
    appId: '1:92826655668:ios:3b578bf5caf38478f170e1',
    messagingSenderId: '92826655668',
    projectId: 'twitter-task-6e6b1',
    storageBucket: 'twitter-task-6e6b1.firebasestorage.app',
    iosBundleId: 'com.example.twitterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqk0lvP3XC3j2Xhl_vqULC01DfzZTzP-A',
    appId: '1:92826655668:ios:3b578bf5caf38478f170e1',
    messagingSenderId: '92826655668',
    projectId: 'twitter-task-6e6b1',
    storageBucket: 'twitter-task-6e6b1.firebasestorage.app',
    iosBundleId: 'com.example.twitterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKtSsZ67inFy0ruAU1DW42nl5X8kbgkMk',
    appId: '1:92826655668:web:d541c3ed7f89a381f170e1',
    messagingSenderId: '92826655668',
    projectId: 'twitter-task-6e6b1',
    authDomain: 'twitter-task-6e6b1.firebaseapp.com',
    storageBucket: 'twitter-task-6e6b1.firebasestorage.app',
    measurementId: 'G-3WZC3E1WMW',
  );
}
